# Generated by Django 3.0.5 on 2020-07-20 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flex_admin',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('4c95cc4f-53bf-490b-b8e1-b5467684d619'), max_length=50),
        ),
    ]
