# Generated by Django 3.0.5 on 2020-07-20 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200720_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='flex_admin',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('98f19b5d-3064-468f-8180-2293d9c203fa'), max_length=50),
        ),
    ]
