# Generated by Django 3.0.5 on 2020-07-20 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('ca7390e5-a3a1-482f-bdb0-ecaee323c83a'), max_length=50),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('cebb456a-150a-4021-be93-d24f3a61e963'), max_length=50),
        ),
    ]
